= REST API in pure Java without any frameworks

== Libs
Lombok https://projectlombok.org/
Logback tutorial: https://stackify.com/logging-logback/
https://docs.vavr.io/





== Building Container Image

Java Docker / OCI Images are known for its large size. For example the default openjdk:17-alpine image with 318 MB
https://hub.docker.com/layers/openjdk/library/openjdk/17-alpine/images/sha256-a996cdcc040704ec6badaf5fecf1e144c096e00231a29188596c784bcf858d05?context=explore

There are plenty of reasons why an image should be as small as possible, so we will try to reduce it.


=== Optimise OpenJDK Size

Since Java 9 and the modular system of java a downsizing of the JavaVM is possible.
For that two commandline tools are essential: jdeps and jlink.

*jdeps* analyzes an existing jar and shows the java module dependencies.
For further details check the spec https://docs.oracle.com/en/java/javase/17/docs/specs/man/jdeps.html

*jlink* assemble and optimize a set of modules and their dependencies into a custom runtime image
For further details check the spec https://docs.oracle.com/en/java/javase/17/docs/specs/man/jlink.html

Lets check the results:

.Build the image
[source, bash]
----
./build-and-push-pure-java-graalvm.sh
----

[source, bash]
----
dive localhost:5003/java-pure-apko-graalvm

5.9 MB  FROM b4fc1b015ed6084
90 MB  COPY /opt/jre-minimal /opt/jre-minimal
3.4 MB  COPY /home/app/target/java-pure-apko-graalvm*jar-with-dependencies.jar /app.jar

Total Image size: 100 MB
----



=== Optimise Base Image for OpenJDK

To build a small base image what prepared for the JDK Wolfi and Apko will be used.

* https://github.com/wolfi-dev/os
* https://edu.chainguard.dev/open-source/wolfi/overview/
* https://github.com/chainguard-dev/apko
* https://edu.chainguard.dev/open-source/apko/overview/

